app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

api_v1:
    prefix: '/api/v1'
    resource: '@AppBundle/Controller/api/v1/'